'use strict'

const FRONTEND_BIND_HOST = '127.0.0.1'
const FRONTEND_PUBLIC_HOST = 'localhost'
const FRONTEND_PORT = 4173
const FRONTEND_ORIGIN = `http://${FRONTEND_PUBLIC_HOST}:${FRONTEND_PORT}`
const BROWSER_AK_PLACEHOLDER = '__BAIDUMAP_RUNTIME_BROWSER_AK__'

module.exports = {
  FRONTEND_BIND_HOST,
  FRONTEND_PUBLIC_HOST,
  FRONTEND_PORT,
  FRONTEND_ORIGIN,
  BROWSER_AK_PLACEHOLDER,
}

